-- AlterEnum
ALTER TYPE "LessonModule" ADD VALUE 'WELCOME';
ALTER TYPE "LessonModule" ADD VALUE 'POSITIVE_PLAY';
ALTER TYPE "LessonModule" ADD VALUE 'CALM_DISCIPLINE';
ALTER TYPE "LessonModule" ADD VALUE 'BIG_FEELINGS_TANTRUMS';
