ALTER TYPE "LessonModule" ADD VALUE IF NOT EXISTS 'GETTING_STARTED';
ALTER TYPE "LessonModule" ADD VALUE IF NOT EXISTS 'DISCIPLINE';
ALTER TYPE "LessonModule" ADD VALUE IF NOT EXISTS 'EMOTIONAL_MASSAGE';
ALTER TYPE "LessonModule" ADD VALUE IF NOT EXISTS 'ADHD';
